(load "lib/draw-line")

(define (segments->painter segment-list)
  (lambda (frame)
          (for-each
           (lambda (segment)
                   (draw-line
                    ((frame-coord-map frame)
                     (start-segment segment))
                    ((frame-coord-map frame)
                     (end-segment segment))))
           segment-list)))

(define outline-painter
  (segments->painter
   (list (make-segment (make-vect 0 0)
                       (make-vect 1 0))
         (make-segment (make-vect 1 0)
                       (make-vect 1 1))
         (make-segment (make-vect 1 1)
                       (make-vect 0 1))
         (make-segment (make-vect 0 1)
                       (make-vect 0 0)))))

(define x-painter
  (segments->painter
   (list (make-segment (make-vect 0 0)
                       (make-vect 1 1))
         (make-segment (make-vect 0 1)
                       (make-vect 1 0)))))

(define diamond-painter
  (segments->painter
   (list (make-segment (make-vect 0 0.5)
                       (make-vect 0.5 0))
         (make-segment (make-vect 0.5 0)
                       (make-vect 1 0.5))
         (make-segment (make-vect 1 0.5)
                       (make-vect 0.5 1))
         (make-segment (make-vect 0.5 1)
                       (make-vect 0 0.5)))))

(define wave
  (segments->painter
   (list (make-segment (make-vect .26 .00)
                       (make-vect .37 .56))
         (make-segment (make-vect .37 .56)
                       (make-vect .16 .48))
         (make-segment (make-vect .16 .48)
                       (make-vect .00 .63))
         (make-segment (make-vect .00 .74)
                       (make-vect .16 .61))
         (make-segment (make-vect .16 .61)
                       (make-vect .31 .70))
         (make-segment (make-vect .31 .70)
                       (make-vect .42 .70))
         (make-segment (make-vect .42 .70)
                       (make-vect .31 .83))
         (make-segment (make-vect .31 .83)
                       (make-vect .41 1.0))
         (make-segment (make-vect .55 1.0)
                       (make-vect .63 .83))
         (make-segment (make-vect .63 .83)
                       (make-vect .55 .70))
         (make-segment (make-vect .55 .70)
                       (make-vect .68 .70))
         (make-segment (make-vect .68 .70)
                       (make-vect 1.0 .42))
         (make-segment (make-vect 1.0 .30)
                       (make-vect .63 .56))
         (make-segment (make-vect .63 .56)
                       (make-vect .79 .00))
         (make-segment (make-vect .65 .00)
                       (make-vect .50 .30))
         (make-segment (make-vect .50 .30)
                       (make-vect .42 .00))
         (make-segment (make-vect .43 .80)
                       (make-vect .45 .76))
         (make-segment (make-vect .45 .76)
                       (make-vect .52 .76))
         (make-segment (make-vect .52 .76)
                       (make-vect .55 .80)))))
