(define sample-emails
  (list (make-kv-pair 'sample-emails (list "cs61a-tb" "cs61a-tc" "mapreduce" "mapreduce is great! lucky students"))
        (make-kv-pair 'sample-emails (list "bot1337" "cs61a-ta" "free ipod now!" "buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "bot1338" "cs61a-tf" "free ipod now!" "buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61a-tf" "cs61a-te" "jokes" "so this bear walks into a bar..."))
        (make-kv-pair 'sample-emails (list "bot1339" "cs61a-te" "free ipod now!" "buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61a-af" "cs61a-ag" "proj4" "help! it's not working!"))
        (make-kv-pair 'sample-emails (list "cs61a-af" "cs61a-ta" "proj4" "i get a problem with okay"))
        (make-kv-pair 'sample-emails (list "cs61a-ta" "cs61a-af" "Re: proj4" "did you forget to return =no-value= ?"))
        (make-kv-pair 'sample-emails (list "cs61a-af" "cs61a-ta" "Re: Re: proj4" "oh wow! no i didn't. Thanks! What a smart TA"))
        (make-kv-pair 'sample-emails (list "bot1340" "cs61a-ta" "free ipod now!" "buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61c-cs" "cs61a-fw" "have you experienced Zelda on Xbox?" "It's so fun! I fully endorse this product and/or services!"))
        (make-kv-pair 'sample-emails (list "cs61c-ug" "cs61c-dz" "lunch on Thursday the 57 of May" "or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "bot8431" "cs61c-tm" "Please finalise" "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot1739" "cs61c-xy" "Hot tip: buy SCOX" "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61b-eu" "cs61b-we" "I think cs61b-fm is curmudgeonous" "do you think they like me?"))
        (make-kv-pair 'sample-emails (list "bot6246" "cs61b-ly" "Christmas special!" "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot8891" "cs61a-tb" "You've already been approved!" "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot9841" "cs61a-lg" "Dating, 15 messages for you, Olga" "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot5864" "cs61a-dj" "h3rbal 3nhancements" "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61a-ei" "cs61b-qn" "breakfast on Tuesday the 05 of February" "or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "bot8148" "cs61c-yi" "Thank you for request." "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot0748" "cs61c-nz" "Christmas special!" "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot2150" "cs61c-mm" "You've already been approved!" "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot5865" "cs61a-de" "h3rbal 3nhancements" "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot8801" "cs61a-uc" "Please finalise" "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot2218" "cs61a-ip" "h3rbal 3nhancements" "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot4735" "cs61a-xd" "Hot tip: buy SCOX" "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot3294" "cs61b-al" "News" "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot5866" "cs61a-dq" "h3rbal 3nhancements" "haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot9841" "cs61b-eu" "Re: Re: proj4" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61a-dj" "bot8891" "breakfast on Tuesday" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61c-nz" "cs61c-yi" "Hot tip: buy SCOX" "Do you think they like me?"))
        (make-kv-pair 'sample-emails (list "cs61a-fw" "cs61c-dz" "h3rbal 3nhancements" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "cs61c-nz" "cs61a-ta" "breakfast on Tuesday" "Do you think they like me?"))
        (make-kv-pair 'sample-emails (list "cs61a-tb" "bot6246" "Thank you for your request" "Did you forget to return =no-value= ?"))
        (make-kv-pair 'sample-emails (list "bot9841" "bot8891" "breakfast on Tuesday" "It\'s so fun! I fully endorse this product!"))
        (make-kv-pair 'sample-emails (list "cs61c-ug" "cs61a-dj" "h3rbal 3nhancements" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "cs61a-ta" "bot0748" "Hot tip: buy SCOX" "Do you think they like me?"))
        (make-kv-pair 'sample-emails (list "bot6246" "cs61c-dz" "h3rbal 3nhancements" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "bot5864" "Re: Re: proj4" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "cs61a-ei" "cs61c-cs" "Dating, 15 messages for you, Olga" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "cs61c-yi" "cs61b-fm" "Dating, 15 messages for you, Olga" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "bot8148" "bot0748" "h3rbal 3nhancements" "Do you think they like me?"))
        (make-kv-pair 'sample-emails (list "cs61a-lg" "cs61c-dz" "Re: Re: proj4" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "cs61c-cs" "bot8431" "You\'ve already been approved!" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "cs61c-cs" "cs61c-dz" "free ipod now!" "Do you think they like me?"))
        (make-kv-pair 'sample-emails (list "cs61a-dj" "bot0748" "free ipod now!" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "bot0748" "cs61a-ei" "Hot tip: buy SCOX" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "cs61a-dj" "breakfast on Tuesday" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61c-dz" "cs61c-nz" "Thank you for your request" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "cs61c-nz" "bot5864" "Thank you for your request" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61b-fm" "bot1340" "Thank you for your request" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "bot6246" "cs61c-cs" "free ipod now!" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "bot8431" "cs61c-nz" "Hot tip: buy SCOX" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "cs61c-yi" "cs61a-dj" "have you experienced Zelda on Xbox?" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "cs61c-nz" "bot9841" "free ipod now!" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "bot6246" "cs61b-we" "lunch on Thursday" "Do you think they like me?"))
        (make-kv-pair 'sample-emails (list "bot8891" "cs61b-qn" "Hot tip: buy SCOX" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61a-ta" "cs61c-yi" "Re: proj4" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "bot1739" "bot6246" "Please finalise" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61a-dj" "bot9841" "Dating, 15 messages for you, Olga" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61b-eu" "cs61a-dj" "Christmas special!" "Hope to see you there!"))
        (make-kv-pair 'sample-emails (list "bot1739" "bot1340" "Re: proj4" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "bot6246" "cs61c-yi" "You\'ve already been approved!" "Hope to see you there!"))
        (make-kv-pair 'sample-emails (list "bot1739" "bot8431" "Thank you for your request" "Hope to see you there!"))
        (make-kv-pair 'sample-emails (list "cs61a-tb" "cs61b-eu" "breakfast on Tuesday" "Did you forget to return =no-value= ?"))
        (make-kv-pair 'sample-emails (list "bot5864" "bot0748" "Please finalise" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61a-fw" "cs61a-tb" "h3rbal 3nhancements" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61c-dz" "bot6246" "free ipod now!" "Hope to see you there!"))
        (make-kv-pair 'sample-emails (list "bot1340" "cs61c-cs" "Re: proj4" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61a-fw" "cs61a-ta" "Dating, 15 messages for you, Olga" "Haha! Buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "bot1340" "h3rbal 3nhancements" "Hope to see you there!"))
        (make-kv-pair 'sample-emails (list "cs61c-yi" "cs61a-ta" "Re: proj4" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61b-fm" "bot5864" "Thank you for your request" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61a-ei" "cs61a-ta" "free ipod now!" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "bot1340" "breakfast on Tuesday" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "bot5864" "cs61c-nz" "You\'ve already been approved!" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "cs61a-tb" "bot8431" "Thank you for your request" "Haha! Buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot5864" "cs61a-dj" "Dating, 15 messages for you, Olga" "Do you think they like me?"))
        (make-kv-pair 'sample-emails (list "cs61c-cs" "bot8431" "Dating, 15 messages for you, Olga" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "cs61c-nz" "bot6246" "Please finalise" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "bot1340" "Re: Re: proj4" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "bot5864" "bot8431" "have you experienced Zelda on Xbox?" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61a-fw" "cs61b-fm" "Re: Re: proj4" "Do you think they like me?"))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "bot8148" "Please finalise" "Do you think they like me?"))
        (make-kv-pair 'sample-emails (list "bot1739" "cs61b-qn" "breakfast on Tuesday" "Haha! Buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61c-dz" "bot8891" "breakfast on Tuesday" "Did you forget to return =no-value= ?"))
        (make-kv-pair 'sample-emails (list "bot6246" "cs61a-fw" "Re: proj4" "It\'s so fun! I fully endorse this product!"))
        (make-kv-pair 'sample-emails (list "cs61c-ug" "cs61a-af" "Thank you for your request" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "cs61a-fw" "cs61c-ug" "Re: Re: proj4" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61c-nz" "bot5864" "Dating, 15 messages for you, Olga" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61a-ei" "cs61b-eu" "Please finalise" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "bot8891" "bot8148" "Hot tip: buy SCOX" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "cs61c-nz" "cs61a-ta" "free ipod now!" "Hope to see you there!"))
        (make-kv-pair 'sample-emails (list "cs61a-tb" "bot8891" "free ipod now!" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot0748" "bot1340" "Please finalise" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "cs61a-dj" "cs61a-tb" "Re: Re: proj4" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "cs61c-ug" "cs61c-yi" "Christmas special!" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "bot8431" "cs61c-nz" "lunch on Thursday" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61b-we" "cs61b-ly" "breakfast on Tuesday" "Hope to see you there!"))
        (make-kv-pair 'sample-emails (list "cs61a-af" "cs61a-lg" "You\'ve already been approved!" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61b-fm" "cs61c-dz" "Hot tip: buy SCOX" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "bot5864" "Christmas special!" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61c-nz" "bot8148" "Christmas special!" "It\'s so fun! I fully endorse this product!"))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "bot0748" "Thank you for your request" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61b-we" "cs61a-dj" "h3rbal 3nhancements" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "cs61b-fm" "breakfast on Tuesday" "It\'s so fun! I fully endorse this product!"))
        (make-kv-pair 'sample-emails (list "cs61b-qn" "cs61c-cs" "You\'ve already been approved!" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "cs61b-qn" "cs61a-ta" "h3rbal 3nhancements" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot8891" "cs61c-cs" "Christmas special!" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61c-cs" "cs61c-yi" "breakfast on Tuesday" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61c-yi" "cs61b-ly" "breakfast on Tuesday" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61b-eu" "cs61c-yi" "Thank you for your request" "Haha! Buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61a-ta" "bot6246" "Dating, 15 messages for you, Olga" "Haha! Buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61a-ei" "cs61c-yi" "have you experienced Zelda on Xbox?" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61b-fm" "bot8891" "Hot tip: buy SCOX" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "cs61a-ta" "Hot tip: buy SCOX" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "cs61b-fm" "bot1739" "Hot tip: buy SCOX" "It\'s so fun! I fully endorse this product!"))
        (make-kv-pair 'sample-emails (list "bot0748" "cs61a-fw" "Christmas special!" "It\'s so fun! I fully endorse this product!"))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "bot1739" "Re: proj4" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "bot9841" "cs61b-eu" "Thank you for your request" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61c-ug" "cs61a-fw" "Thank you for your request" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "bot0748" "cs61c-dz" "Dating, 15 messages for you, Olga" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "bot2150" "cs61b-ly" "h3rbal 3nhancements" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61a-fw" "cs61a-lg" "have you experienced Zelda on Xbox?" "Haha! Buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot8891" "cs61b-we" "Re: proj4" "Did you forget to return =no-value= ?"))
        (make-kv-pair 'sample-emails (list "bot0748" "cs61a-fw" "Dating, 15 messages for you, Olga" "Do you think they like me?"))
        (make-kv-pair 'sample-emails (list "cs61a-ei" "bot1340" "You\'ve already been approved!" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "cs61a-tb" "cs61a-ei" "breakfast on Tuesday" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "cs61a-fw" "cs61c-ug" "have you experienced Zelda on Xbox?" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "bot2150" "cs61c-yi" "Please finalise" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "cs61c-yi" "bot1739" "Hot tip: buy SCOX" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot6246" "cs61b-qn" "Please finalise" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "cs61a-af" "bot1340" "have you experienced Zelda on Xbox?" "It\'s so fun! I fully endorse this product!"))
        (make-kv-pair 'sample-emails (list "cs61a-dj" "cs61b-fm" "have you experienced Zelda on Xbox?" "Hope to see you there!"))
        (make-kv-pair 'sample-emails (list "bot8891" "cs61b-ly" "Re: proj4" "Hope to see you there!"))
        (make-kv-pair 'sample-emails (list "cs61a-tb" "cs61c-ug" "Re: proj4" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "cs61a-tb" "cs61a-lg" "Re: Re: proj4" "Haha! Buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot1340" "cs61c-cs" "Christmas special!" "Do you think they like me?"))
        (make-kv-pair 'sample-emails (list "bot8431" "cs61a-dj" "You\'ve already been approved!" "Did you forget to return =no-value= ?"))
        (make-kv-pair 'sample-emails (list "cs61b-fm" "bot8431" "h3rbal 3nhancements" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "cs61a-ta" "cs61a-dj" "Re: proj4" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61b-we" "bot2150" "breakfast on Tuesday" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "cs61c-yi" "Christmas special!" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot1739" "cs61b-qn" "Dating, 15 messages for you, Olga" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61c-ug" "bot0748" "You\'ve already been approved!" "Hope to see you there!"))
        (make-kv-pair 'sample-emails (list "cs61b-we" "bot1739" "Please finalise" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61c-cs" "bot5864" "Please finalise" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "cs61a-lg" "cs61c-dz" "You\'ve already been approved!" "Hope to see you there!"))
        (make-kv-pair 'sample-emails (list "bot0748" "cs61b-we" "You\'ve already been approved!" "It\'s so fun! I fully endorse this product!"))
        (make-kv-pair 'sample-emails (list "cs61a-tb" "cs61a-ta" "Re: proj4" "Hope to see you there!"))
        (make-kv-pair 'sample-emails (list "cs61c-ug" "bot2150" "breakfast on Tuesday" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61b-eu" "cs61c-dz" "You\'ve already been approved!" "Haha! Buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61a-fw" "cs61a-dj" "Thank you for your request" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61b-fm" "cs61c-yi" "breakfast on Tuesday" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot6246" "bot8891" "h3rbal 3nhancements" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "cs61c-cs" "bot2150" "Dating, 15 messages for you, Olga" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "cs61a-fw" "bot0748" "h3rbal 3nhancements" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "bot8148" "cs61b-fm" "have you experienced Zelda on Xbox?" "Haha! Buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61c-nz" "cs61c-cs" "Hot tip: buy SCOX" "Haha! Buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot8148" "cs61b-ly" "lunch on Thursday" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "cs61b-qn" "cs61c-nz" "have you experienced Zelda on Xbox?" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61a-tb" "bot2150" "Hot tip: buy SCOX" "Hope to see you there!"))
        (make-kv-pair 'sample-emails (list "cs61a-lg" "cs61a-tb" "free ipod now!" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61c-nz" "cs61c-ug" "Re: proj4" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "bot9841" "Re: proj4" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot8148" "cs61b-we" "Christmas special!" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "bot1340" "bot5864" "Christmas special!" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "bot1340" "bot8148" "Please finalise" "Do you think they like me?"))
        (make-kv-pair 'sample-emails (list "cs61b-qn" "cs61c-dz" "Thank you for your request" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61a-fw" "cs61a-ta" "Re: proj4" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "bot1340" "bot2150" "lunch on Thursday" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "cs61a-af" "bot1340" "free ipod now!" "It\'s so fun! I fully endorse this product!"))
        (make-kv-pair 'sample-emails (list "cs61a-tb" "cs61c-nz" "Hot tip: buy SCOX" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "cs61a-tb" "cs61c-ug" "Re: proj4" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot8148" "bot5864" "breakfast on Tuesday" "Do you think they like me?"))
        (make-kv-pair 'sample-emails (list "bot1739" "cs61a-ei" "free ipod now!" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "cs61b-eu" "cs61a-tb" "have you experienced Zelda on Xbox?" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "bot8431" "bot1739" "breakfast on Tuesday" "Oh wow! No I didn\'t. Thanks!"))
        (make-kv-pair 'sample-emails (list "bot2150" "cs61b-ly" "lunch on Thursday" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "cs61a-af" "cs61c-nz" "lunch on Thursday" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "cs61c-cs" "cs61b-we" "breakfast on Tuesday" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "bot5864" "cs61b-fm" "h3rbal 3nhancements" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "bot6246" "cs61b-eu" "You\'ve already been approved!" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "bot2150" "cs61b-fm" "Thank you for your request" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "cs61a-tb" "cs61a-lg" "free ipod now!" "Haha! Buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61a-lg" "bot6246" "Re: proj4" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "bot8148" "cs61a-ei" "breakfast on Tuesday" "Hope to see you there!"))
        (make-kv-pair 'sample-emails (list "cs61a-ei" "bot5864" "Re: proj4" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "cs61a-tb" "h3rbal 3nhancements" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61b-qn" "bot9841" "Please finalise" "Haha! buy our stuff!"))
        (make-kv-pair 'sample-emails (list "cs61a-dj" "cs61c-ug" "Hot tip: buy SCOX" "Did you forget to return =no-value= ?"))
        (make-kv-pair 'sample-emails (list "cs61c-dz" "bot2150" "free ipod now!" "You\'ve been approved for a special offer."))
        (make-kv-pair 'sample-emails (list "cs61c-ug" "bot2150" "breakfast on Tuesday" "Check your inbox for details."))
        (make-kv-pair 'sample-emails (list "bot1340" "cs61a-fw" "have you experienced Zelda on Xbox?" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61c-nz" "bot9841" "breakfast on Tuesday" "Buy herbal ipod enhancer"))
        (make-kv-pair 'sample-emails (list "cs61b-ly" "cs61c-yi" "Re: Re: proj4" "Or will you still be working on proj4?"))
        (make-kv-pair 'sample-emails (list "cs61a-hx" "cs61a-pz" "I think cs61a-np is angsty" "so watch out"))))
