(load "test")
(load "jocker-best-total")

(test "Should return 19" (best-total '(ad 8s)) 19)
(test "Should return 14" (best-total '(ad 8s 5h)) 14)
(test "Should return 21" (best-total '(ad as 9h)) 21)
(test "Should return 20" (best-total '(as 9d)) 20)
(test "Should return 21" (best-total '(kd as)) 21)
(test "Should return 17" (best-total '(7h ad 9c)) 17)
(test "Should return 13" (best-total '(3s 9d as)) 13)
(test "Should return 19" (best-total '(5c ad 3h)) 19)
(test "Should return 21" (best-total '(as as 9d)) 21)
(test "Should return 11" (best-total '(as)) 11)
(test "Should return 10" (best-total '(kd qh)) 20)
(test "Should return 18" (best-total '(8c qd)) 18)
(test "Should return 16" (best-total '(6s 10d)) 16)
(test "Should return 9" (best-total '(9s)) 9)
(test "Should return 7" (best-total '(7d)) 7)
(test "Should return 20" (best-total '(kh qs)) 20)
(test "Should return 12" (best-total '(ad ad)) 12)
(test "Should return 13" (best-total '(2d ad)) 13)
(test "Should return 11" (best-total '(as ad 9d)) 21)

;; test with jocker cards
(test "Should return 11" (best-total '(jocker)) 11)
(test "Should return 19" (best-total '(8d jocker)) 19)
(test "Should return 21" (best-total '(qd jocker)) 21)
(test "Should return 21" (best-total '(qd jocker)) 21)
(test "Should return 17" (best-total '(2d 4d jocker)) 17)
(test "Should return 21" (best-total '(10d 10h jocker)) 21)
